/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ToadzgotchiPetsContract,
  ToadzgotchiPetsContractInterface,
} from "../ToadzgotchiPetsContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "toadzgotchisOwned",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ToadzgotchiPetsContract__factory {
  static readonly abi = _abi;
  static createInterface(): ToadzgotchiPetsContractInterface {
    return new utils.Interface(_abi) as ToadzgotchiPetsContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ToadzgotchiPetsContract {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ToadzgotchiPetsContract;
  }
}
