/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ToadzInterface,
  ToadzInterfaceInterface,
} from "../ToadzInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ToadzInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ToadzInterfaceInterface {
    return new utils.Interface(_abi) as ToadzInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ToadzInterface {
    return new Contract(address, _abi, signerOrProvider) as ToadzInterface;
  }
}
