/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Toadzgotchi } from "./Toadzgotchi";

export { Toadzgotchi__factory } from "./factories/Toadzgotchi__factory";
