name: Decay toad stats workflow
env:
  REPO_OWNER: jbarrasso
  REPO_NAME: toadzgotchi-app
  GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
on:
  repository_dispatch:
    types: [run_decay]
jobs:
  decay:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route to decay toad stats by 1
        run:
        curl --request PATCH \
        --url 'https://${{process.env.NEXT_PUBLIC_VERCEL_URL}}/api/toadStats/decay' \
        --header 'Authorization: Bearer ${{ secrets.DECAY_API_TOKEN }}' \
        --data '{ "toadId" : ${{ github.event.client_payload.toadId }} }'
