name: Test Push Main
on:
  push:
jobs:
  decay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Message
        run: echo "Automatically print a message once pushed to main!"
