name: Test Decay Main
on:
  repository_dispatch:
    types: [run_decay]
jobs:
  decay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call API route to decay toad stats by 1
        run: |
          curl --request PATCH \
          --url 'https://www.toadzgotchi.com' \
          --header 'Authorization: Bearer ${{ secrets.DECAY_API_TOKEN }}' \
          --data '{ "toadId" : ${{ github.event.client_payload.toadId }} }'
